### ISSUE TITLE
`exp` doesn't work for sparse arrays

### ISSUE THREAD

**Issue by birkmichael** [JuliaSparse/SparseArrays.jl#78]
It seems that matrix exponentiation via `exp(sparsearray)` doesn't work, and one needs to make the matrix dense first. There is a sparse-efficient algorithm for this problem in MATLAB [here](https://github.com/fmentink/fastExpm), which I want to port to Julia. Would this be fine? In which .jl file should I put it? It looks like it should be `linalg.jl`, but I'm not sure.

**Comment by stevengj** [comment]
It seems like that would be better as a package, especially since whether that algorithm works well is likely to be very problem-dependent.  In fact, it looks like it already is available as a package: https://github.com/fmentink/FastExpm.jl

There are also multiple packages to compute the *action* of the matrix exponential on a vector via iterati e methods (which exploit sparsity or other structures), which can be much more efficient than computing the whole exponential matrix: https://github.com/SciML/ExponentialUtilities.jl and https://github.com/sethaxen/ExponentialAction.jl https://github.com/Jutho/KrylovKit.jl

**Comment by goggle** [comment]
Related: https://github.com/JuliaLang/julia/issues/32899

**Comment by birkmichael** [comment]
Comments noted, didn't look into the repository properly.
